exerciseTypes = ['Assisted Dip',
'Bench Press',
'Cable Chest Press',
'Clap Push-Up',
'Close-Grip Bench Press',
'Decline Bench Press',
'Decline Push-Up',
'Dumbbell Chest Fly',
'Dumbbell Chest Press',
'Dumbbell Decline Chest Press',
'Dumbbell Pullover',
'Incline Bench Press',
'Incline Dumbbell Press',
'Incline Push-Up',
'Pec Deck',
'Push-Up',
'Seated Cable Chest Fly',
'Smith Machine Bench Press',
'Smith Machine Incline Bench Press',
'Smith Machine Reverse Grip Bench Press',
'Standing Cable Chest Fly',
'Arnold Press',
'Barbell Front Raise',
'Barbell Rear Delt Row',
'Barbell Upright Row',
'Behind the Neck Press',
'Cable Front Raise',
'Cable Lateral Raise',
'Cable Rear Delt Row',
'Dumbbell Front Raise',
'Dumbbell Lateral Raise',
'Dumbbell Rear Delt Row',
'Dumbbell Shoulder Press',
'Face Pull',
'Front Hold',
'Handstand Push-Up',
'Landmine Press',
'One-Arm Landmine Press',
'Overhead Press',
'Plate Front Raise',
'Push Press',
'Seated Dumbbell Shoulder Press',
'Seated Barbell Overhead Press',
'Seated Kettlebell Press',
'Seated Smith Machine Shoulder Press',
'Barbell Curl',
'Barbell Preacher Curl',
'Cable Crossover Bicep Curl',
'Cable Curl With Bar',
'Cable Curl With Rope',
'Concentration Curl',
'Drag Curl',
'Dumbbell Curl',
'Dumbbell Preacher Curl',
'Hammer Curl',
'Incline Dumbbell Curl',
'Spider Curl',
'Barbell Standing Triceps Extension',
'Barbell Incline Triceps Extension',
'Barbell Lying Triceps Extension',
'Crossbody Cable Triceps Extension',
'Close-Grip Push-Up',
'Dumbbell Lying Triceps Extension',
'Dumbbell Standing Triceps Extension',
'Overhead Cable Triceps Extension',
'Tricep Bodyweight Extension',
'Tricep Pushdown With Bar',
'Tricep Pushdown With Rope',
'Air Squat',
'Barbell Hack Squat',
'Barbell Lunge',
'Barbell Walking Lunge',
'Belt Squat',
'Body Weight Lunge',
'Box Jump',
'Box Squat',
'Bulgarian Split Squat',
'Cable Machine Hip Adduction',
'Chair Squat',
'Curtsy Lunge',
'Dumbbell Lunge',
'Dumbbell Walking Lunge',
'Dumbbell Squat',
'Front Squat',
'Glute Ham Raise',
'Goblet Squat',
'Hack Squat Machine',
'Half Air Squat',
'Hip Adduction Against Band',
'Hip Adduction Machine',
'Jumping Lunge',
'Kettlebell Thrusters',
'Landmine Hack Squat',
'Landmine Squat',
'Leg Extension',
'Leg Press',
'One-Legged Leg Extension',
'One-Legged Lying Leg Curl',
'One-Legged Seated Leg Curl',
'Pause Squat',
'Pistol Squat',
'Romanian Deadlift',
'Safety Bar Squat',
'Seated Leg Curl',
'Side Lunges (Bodyweight)',
'Smith Machine Bulgarian Split Squat',
'Smith Machine Front Squat',
'Smith Machine Squat',
'Squat',
'Standing Cable Leg Extension',
'Step Up',
'Assisted Chin-Up',
'Assisted Pull-Up',
'Back Extension',
'Banded Muscle-Up',
'Barbell Row',
'Barbell Shrug',
'Block Clean',
'Block Snatch',
'Cable Close Grip Seated Row', 
'Cable Wide Grip Seated Row',
'Chest to Bar',
'Chin-Up',
'Clean',
'Clean and Jerk',
'Close-Grip Chin-Up',
'Close-Grip Lat Pulldown',
'Deadlift',
'Deficit Deadlift',
'Dumbbell Deadlift',
'Dumbbell Row',
'Dumbbell Shrug',
'Floor Back Extension',
'Good Morning',
'Gorilla Row',
'Hang Clean',
'Hang Power Clean',
'Hang Power Snatch',
'Hang Snatch',
'Inverted Row',
'Inverted Row with Underhand Grip',
'Jefferson Curl',
'Jumping Muscle-Up',
'Kettlebell Clean',
'Kettlebell Clean & Jerk',
'Kettlebell Clean & Press',
'Kettlebell Swing',
'Kroc Row',
'Lat Pulldown With Pronated Grip',
'Lat Pulldown With Supinated Grip',
'Muscle-Up (Bar)',
'Muscle-Up (Rings)',
'Neutral Close-Grip Lat Pulldown',
'One-Handed Cable Row',
'One-Handed Kettlebell Swing',
'One-Handed Lat Pulldown',
'Pause Deadlift',
'Pendlay Row',
'Power Clean',
'Power Snatch',
'Pull-Up',
'Pull-Up With a Neutral Grip',
'Rack Pull',
'Renegade Row',
'Ring Pull-Up',
'Ring Row',
'Scap Pull-Up',
'Seal Row',
'Seated Machine Row',
'Single Leg Deadlift with Kettlebell',
'Smith Machine One-Handed Row',
'Snatch',
'Snatch Grip Deadlift',
'Stiff-Legged Deadlift',
'Straight Arm Lat Pulldown',
'Sumo Deadlift',
'Superman Raise',
'T-Bar Row',
'Towel Row',
'Trap Bar Deadlift With High Handles',
'Trap Bar Deadlift With Low Handles',
'Banded Side Kicks',
'Cable Pull Through',
'Cable Machine Hip Abduction',
'Clamshells',
'Cossack Squat',
'Death March with Dumbbells',
'Donkey Kicks',
'Dumbbell Romanian Deadlift',
'Dumbbell Frog Pumps',
'Fire Hydrants',
'Frog Pumps',
'Glute Bridge',
'Hip Abduction Against Band',
'Hip Abduction Machine',
'Hip Thrust',
'Hip Thrust Machine',
'Hip Thrust With Band Around Knees',
'Lateral Walk With Band',
'Machine Glute Kickbacks',
'One-Legged Glute Bridge',
'One-Legged Hip Thrust',
'Reverse Hyperextension',
'Romanian Deadlift',
'Smith Machine Hip Thrust',
'Single Leg Romanian Deadlift',
'Standing Hip Abduction Against Band',
'Standing Glute Kickback in Machine',
'Standing Glute Push Down',
'Step Up',
'Ball Slams',
'Bicycle Crunch',
'Cable Crunch',
'Copenhagen Plank',
'Core Twist',
'Crunch',
'Dead Bug',
'Dead Bug With Dumbbells',
'Dragon Flag',
'Dumbbell Side Bend',
'Hanging Knee Raise',
'Hanging Leg Raise',
'Hanging Sit-Up',
'Hanging Windshield Wiper',
'High to Low Wood Chop with Band',
'High to Low Wood Chop with Cable',
'Hollow Body Crunch',
'Hollow Hold',
'Horizontal Wood Chop with Band',
'Horizontal Wood Chop with Cable',
'Jackknife Sit-Up',
'Kettlebell Plank Pull Through',
'Kneeling Ab Wheel Roll-Out',
'Kneeling Plank',
'Kneeling Side Plank',
'L-Sit',
'Lying Leg Raise',
'Lying Windshield Wiper',
'Lying Windshield Wiper with Bent Knees',
'Machine Crunch',
'Mountain Climbers',
'Oblique Crunch',
'Oblique Sit-Up',
'Plank',
'Plank with Leg Lifts',
'Plank with Shoulder Taps',
'Side Plank',
'Sit-Up',
'Weighted Plank',
'Calves Exercises',
'Barbell Standing Calf Raise',
'Barbell Seated Calf Raise',
'Donkey Calf Raise',
'Eccentric Heel Drop',
'Heel Raise',
'Seated Calf Raise',
'Standing Calf Raise',
'Forearm Flexors & Grip Exercises',
'Barbell Wrist Curl',
'Barbell Wrist Curl Behind the Back',
'Bar Hang',
'Dumbbell Wrist Curl',
'Farmers Walk',
'Fat Bar Deadlift',
'Gripper',
'One-Handed Bar Hang',
'Plate Pinch',
'Plate Wrist Curl',
'Towel Pull-Up',
'Wrist Roller']